services:
  backend:
    container_name: backend
    image: 221082215561.dkr.ecr.us-east-1.amazonaws.com/rohlik-app:backend-latest
    pull_policy: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: 221082215561.dkr.ecr.us-east-1.amazonaws.com/rohlik-app:frontend-latest
    pull_policy: always
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge